name: Quicksilver
main: com.minecarts.quicksilver.Quicksilver
version: ${pom.version}
website: http://minecarts.com/
author: verrier
description: Pluggin to allow for per player invisiblity
commands:
    vanish:
        description: Toggle invisiblity on yourself or another player
        usage: "/<command> [player]"
    aggro:
        description: Toggle monster aggro on yourself or another player
        usage: "/<command> [player]"
permissions:
    quicksilver.vanish.*:
        description: "Access to all vanish commands"
        children:
            quicksilver.vanish.self: true
            quicksilver.vanish.other: true
    quicksilver.aggro.*:
            description: "Access to all aggro commands"
            children:
                quicksilver.vanish.self: true
                quicksilver.vanish.other: true
    quicksilver.vanish.self:
        description: "Allow for vanishing on yourself"
        default: op
    quicksilver.vanish.other:
        description: "Vanish another player"
        default: op
    quicksilver.vanish.list:
        description: "List vanished players"
        default: op
    quicksilver.vanish.see:
        description: "See vanished players"
        default: op
    quicksilver.aggro.self:
        description: "Allow for aggro blocking on yourself"
        default: op
    quicksilver.aggro.other:
        description: "aggro blocking another player"
        default: op
    quicksilver.aggro.list:
        description: "List players who are not aggroable"
        default: op