name: Quicksilver
description: Per-player invisiblity and aggro control
author: verrier, megabytes
website: http://www.minecarts.com/

main: com.minecarts.quicksilver.Quicksilver
version: ${pom.version}


commands:
    vanish:
        aliases: [poof]
        description: Toggle invisiblity on yourself or another player
        usage: "/<command> [player]"
    aggro:
        aliases: [agro]
        description: Toggle monster aggro on yourself or another player
        usage: "/<command> [player]"
        
        
permissions:
  
    #vanish
    quicksilver.vanish.*:
        description: "Access to all vanish commands"
        children:
            quicksilver.vanish.self: true
            quicksilver.vanish.other: true
            quicksilver.vanish.list: true
    quicksilver.vanish.self:
        description: "Allow for vanishing on yourself"
        default: op
    quicksilver.vanish.other:
        description: "Vanish another player"
        default: op
    quicksilver.vanish.list:
        description: "List vanished players"
        default: op
    quicksilver.vanish.see:
        description: "See vanished players"
        default: op
    quicksilver.aggro.always:
        description: "Always vanish"
        default: false
        
    #deaggro
    quicksilver.aggro.*:
            description: "Access to all aggro commands"
            children:
                quicksilver.aggro.self: true
                quicksilver.aggro.other: true
                quicksilver.aggro.list: true
    quicksilver.aggro.self:
        description: "Allow for aggro blocking on yourself"
        default: op
    quicksilver.aggro.other:
        description: "aggro blocking another player"
        default: op
    quicksilver.aggro.list:
        description: "List players who are not aggroable"
        default: op
    quicksilver.aggro.always:
        description: "Always deaggro"
        default: false